main: fr.cookyy.admin.AdminSystemMain
name: AdminSystem
author: Cookyy_ 
version: '10.2'
description: AdminSystem - /admin - 1.9 > 1.13
commands: 
   admin:
     description: Open GUI 
     permission: adminfr.admin
     default: op
   adminhelp:
     description: Help plugin  
     permission: adminfr.adminhelp
   adminclear:
     description: Clear Inventory 
     permission: adminfr.clear 
   adminhat:
     description: News Hats 
     permission: adminfr.adminhat
   adminmute:
     description: Mute Player
     permission: adminfr.adminmute
   admininvsee:
     description: InvSee
     permission: adminfr.admininvsee
   alert:
     description: Send Alert Server
     permission: adminfr.alert
   rtp:
     description: RandomTP
     permission: adminfr.rtp
   msg:
    description: Send Message
    aliases: [m]
   reply:
    description: Reply Message
    aliases: [r]
   info:
    description: Info Serveur [Forum, Web, YouTube]
   broadcast: 
    permission: adminfr.broadcast